services:
  - type: web
    name: messaging-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        value: postgresql://messaging_db_wdtp_user:CrVGoDBg9vsd8DNQRflsISfmRuoXo5C8@dpg-d5pivf8gjchc73dvgtb0-a/messaging_db_wdtp
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: messaging-app.onrender.com,localhost,127.0.0.1
      - key: DEBUG
        value: "False"
    healthCheckPath: /api/schema/swagger-ui/
    autoDeploy: true
    plan: free
    numInstances: 1
